# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-tcg-api-gateway:
    build:
      target: development
    image: ffc-tcg-api-gateway-development
    container_name: ffc-tcg-api-gateway-development
    ports:
      - "3004:3004"
      - "9029:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
