services:
  ffc-tcg-api-gateway:
    build:
      context: .
      target: production
    image: ffc-tcg-api-gateway
    container_name: ffc-tcg-api-gateway
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-api-gateway-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
